### ISSUE TITLE
Pretty URLs don't work

### ISSUE THREAD

**Issue by samullman** [meancoffee/website#16]
@calebeby the current setup is how I thought you explained how the blocks work

**Comment by samullman** [comment]
branch mean_coffee

**Comment by calebeby** [comment]
Can you separate these into their own issues please

**Comment by calebeby** [comment]
I fixed the blocks in https://github.com/meancoffee/website/tree/update_site

**Comment by samullman** [comment]
<img width="413" alt="screen shot 2017-06-30 at 6 16 53 pm" src="https://user-images.githubusercontent.com/10147333/27758038-5a0c9eb2-5dc0-11e7-8ef6-84b18d04803f.png">

**Comment by calebeby** [comment]
Try coffee.html

**Comment by calebeby** [comment]
Sometimes checking the `public` folder can help you figure out what's gone wrong

**Comment by calebeby** [comment]
I will look into browsersync config for going without .html

**Comment by calebeby** [comment]
But for now stick to .html

**Comment by samullman** [comment]
<img width="1176" alt="screen shot 2017-06-30 at 8 52 45 pm" src="https://user-images.githubusercontent.com/10147333/27758931-233417ce-5dd6-11e7-9d8f-b93b91740552.png">

**Comment by calebeby** [comment]
What do you mean? Coffee.sml is compiled into coffee.html

**Comment by calebeby** [comment]
What I mean is that you should make your links point to /coffee.html for now

**Comment by calebeby** [comment]
until I find out how to have pretty urls with browsersync

**Comment by calebeby** [comment]
OK I fixed it in 19f3d67
