### ISSUE TITLE
resize page to toggle menus

### ISSUE THREAD

**Issue by samullman** [meancoffee/website#17]
I am having trouble attaching the correct listener to the body tag. app.js contains the code I presume would be the correct start

**Comment by calebeby** [comment]
Yup `app.js` is the correct file. You'll need to be more specific if you want me to help.

**Comment by samullman** [comment]
`var body = $('body')
body.addEventListener('onresize', e => {
  if (e.width < 994) {
    // show side menu button
  } else {
    // show regular menu
  }
})
`

**Comment by samullman** [comment]
```
var foo = bar
```

**Comment by calebeby** [comment]
Which branch are you working on?

**Comment by samullman** [comment]
mean_coffee

**Comment by calebeby** [comment]
What happened, what did you expect to happen?

**Comment by samullman** [comment]
<img width="413" alt="screen shot 2017-06-30 at 6 16 53 pm" src="https://user-images.githubusercontent.com/10147333/27758038-5a0c9eb2-5dc0-11e7-8ef6-84b18d04803f.png">

**Comment by samullman** [comment]
Sorry I'm getting my issues confused...

**Comment by samullman** [comment]
I get an error that i.addEventListener is not a function... 

i refers to the body variable after being uglified...

**Comment by calebeby** [comment]
What error?

**Comment by samullman** [comment]
<img width="425" alt="screen shot 2017-06-30 at 6 24 07 pm" src="https://user-images.githubusercontent.com/10147333/27758082-56b98d78-5dc1-11e7-8d58-5f7256a6a7cc.png">

**Comment by calebeby** [comment]
console.log(s)

**Comment by calebeby** [comment]
or console.log(body)

**Comment by calebeby** [comment]
document.querySelectorAll returns an array

**Comment by samullman** [comment]
<img width="131" alt="screen shot 2017-06-30 at 6 26 46 pm" src="https://user-images.githubusercontent.com/10147333/27758099-b49ddba6-5dc1-11e7-8ccd-9114e9c13703.png">

so body[0].addEventListener

**Comment by calebeby** [comment]
so use $('body')[0]

**Comment by samullman** [comment]
Right, I had tried this first and it hadn't worked... Lemme check

**Comment by calebeby** [comment]
or document.body

**Comment by calebeby** [comment]
document.body is probably the way to go

**Comment by samullman** [comment]
found solution
```
window.addEventListener('resize', e => {
  if (e.width < 994) {
    console.log(e);
    // show side menu button
  } else {
    console.log(e);
    // show regular menu
  }
})
```
thanks

**Comment by calebeby** [comment]
So in this case you should definitely use CSS media queries rather than JS

**Comment by samullman** [comment]
OK

**Comment by calebeby** [comment]
We are using rupture as a shorthand for that

**Comment by calebeby** [comment]
so you can say +above(something px)

**Comment by calebeby** [comment]
https://github.com/meancoffee/website/blob/mean_coffee/app/styles.styl#L63

**Comment by samullman** [comment]
done, much better
